# Generated by Django 4.1 on 2022-12-18 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auction_item_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="auction_item", name="close",),
        migrations.RemoveField(model_name="auction_item", name="name",),
        migrations.RemoveField(model_name="auction_item", name="winner",),
        migrations.AddField(
            model_name="auction_item",
            name="description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="auction_item",
            name="title",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bidding",
            name="close",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bidding",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
