# Generated by Django 4.1 on 2022-12-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_auction_item_seller"),
    ]

    operations = [
        migrations.RemoveField(model_name="bidding", name="close",),
        migrations.AddField(
            model_name="bidding",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
