# Generated by Django 4.1 on 2022-12-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_remove_bidding_close_bidding_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidding",
            name="current_bid",
            field=models.IntegerField(null=True),
        ),
    ]
