# Generated by Django 4.1 on 2022-12-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_bidding_current_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
