# Generated by Django 4.1 on 2022-12-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_auction_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidding",
            name="current_bid",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
