# Generated by Django 4.1 on 2022-12-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_bidding_current_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidding",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_info",
                to="auctions.auction_item",
            ),
        ),
    ]
