# Generated by Django 4.1 on 2022-12-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_alter_auction_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_item",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
