# Generated by Django 4.1 on 2022-12-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_auction_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_item",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
