# Generated by Django 4.1 on 2022-12-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_alter_bidding_current_bid_alter_bidding_item"),
    ]

    operations = [
        migrations.RemoveField(model_name="bidding", name="active",),
        migrations.AddField(
            model_name="auction_item",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="auction_item",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
