# Generated by Django 4.1 on 2022-12-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_remove_bidding_active_auction_item_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidding",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_item",
                to="auctions.auction_item",
                unique=True,
            ),
        ),
    ]
