# Generated by Django 4.1 on 2022-12-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_alter_bidding_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidding",
            name="bid_price",
            field=models.IntegerField(null=True),
        ),
    ]
