# Generated by Django 4.1 on 2022-12-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_bidding_bid_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="bidding", name="current_bid",),
        migrations.AddField(
            model_name="auction_item",
            name="current_bid",
            field=models.IntegerField(null=True),
        ),
    ]
