# Generated by Django 4.1 on 2022-12-21 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0018_remove_bidding_current_bid_auction_item_current_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidding",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_item",
                to="auctions.auction_item",
            ),
        ),
    ]
