# Generated by Django 4.1 on 2022-12-21 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0019_alter_bidding_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidding",
            name="bidder",
            field=models.ManyToManyField(
                related_name="bidder", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
