# Generated by Django 4.1 on 2022-12-21 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0020_bidding_bidder"),
    ]

    operations = [
        migrations.RemoveField(model_name="bidding", name="bidder",),
        migrations.AddField(
            model_name="bidding",
            name="bidder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
