# Generated by Django 4.1 on 2022-12-21 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0021_remove_bidding_bidder_bidding_bidder"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_item",
            name="watchlist_user",
            field=models.ManyToManyField(
                related_name="watchlist_item", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
