# Generated by Django 4.1 on 2022-12-21 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0022_auction_item_watchlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_item",
            name="watchlist_user",
            field=models.ManyToManyField(
                null=True, related_name="watchlist_item", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
